--
-- TB_USER  (Table) 
--
CREATE TABLE TB_USER(
  ID    INTEGER                                 NOT NULL,
  NAME  VARCHAR2(60 BYTE)                           NULL,
  CODE  VARCHAR2(10 BYTE)                           NULL
);


--
-- TB_RESERVE_PERIOD  (Table) 
--
CREATE TABLE TB_RESERVE_PERIOD(
  ID          INTEGER                           NOT NULL,
  START_DATE  DATE                              NOT NULL,
  END_DATE    DATE                              NOT NULL,
  AVERAGE     NUMBER                                NULL
);


--
-- TB_PROPERTIES  (Table) 
--
CREATE TABLE TB_PROPERTIES(
  KEY    VARCHAR2(128 BYTE)                     NOT NULL,
  VALUE  VARCHAR2(2048 BYTE)                        NULL
);


--
-- TB_RESERVE_CLOSED_DATES  (Table) 
--
CREATE TABLE TB_RESERVE_CLOSED_DATES(
  CLOSED_DATE  DATE                             NOT NULL
);


--
-- TB_RESERVE_PUBLISH  (Table) 
--
CREATE TABLE TB_RESERVE_PUBLISH(
  PUBLISH_DATE  DATE                            NOT NULL,
  BALANCE       NUMBER                          NOT NULL,
  DEPOSIT       NUMBER                              NULL,
  LENDING       NUMBER                              NULL
);

--
-- Indexs 
--
CREATE UNIQUE INDEX TB_PROPERTIES_PK ON TB_PROPERTIES(KEY);
CREATE UNIQUE INDEX PK_RESERVE_CLOSED_DATES ON TB_RESERVE_CLOSED_DATES(CLOSED_DATE);
CREATE INDEX INDEX_FBI_YEAR_CLOSED_DATES ON TB_RESERVE_CLOSED_DATES(CLOSED_DATE, 'yyyy');
CREATE UNIQUE INDEX PK_RESERVE_PERIOD ON TB_RESERVE_PERIOD(ID);
CREATE UNIQUE INDEX INDEX_RESERVE_PERIOD ON TB_RESERVE_PERIOD(START_DATE);
CREATE UNIQUE INDEX PK_RESERVE_PUBLISH ON TB_RESERVE_PUBLISH(PUBLISH_DATE);
CREATE UNIQUE INDEX PK_TB_USER ON TB_USER(ID);

-- 
-- Non Foreign Key Constraints 
-- 
ALTER TABLE TB_USER ADD ( CONSTRAINT PK_TB_USER PRIMARY KEY (ID));
ALTER TABLE TB_RESERVE_PERIOD ADD (  CONSTRAINT PK_RESERVE_PERIOD PRIMARY KEY (ID));
ALTER TABLE TB_PROPERTIES ADD (  CONSTRAINT TB_PROPERTIES_PK PRIMARY KEY (KEY));
ALTER TABLE TB_RESERVE_CLOSED_DATES ADD (  CONSTRAINT PK_RESERVE_CLOSED_DATES PRIMARY KEY (CLOSED_DATE));
ALTER TABLE TB_RESERVE_PUBLISH ADD (  CONSTRAINT PK_RESERVE_PUBLISH PRIMARY KEY (PUBLISH_DATE));

-- 
-- Insert
-- 
SET DEFINE OFF;
Insert into TB_RESERVE_CLOSED_DATES   (CLOSED_DATE) Values   (TO_DATE('01/01/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TB_RESERVE_CLOSED_DATES   (CLOSED_DATE) Values   (TO_DATE('04/22/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TB_RESERVE_CLOSED_DATES   (CLOSED_DATE) Values   (TO_DATE('04/25/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TB_RESERVE_CLOSED_DATES   (CLOSED_DATE) Values   (TO_DATE('05/01/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TB_RESERVE_CLOSED_DATES   (CLOSED_DATE) Values   (TO_DATE('12/25/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
Insert into TB_RESERVE_CLOSED_DATES   (CLOSED_DATE) Values   (TO_DATE('12/26/2011 00:00:00', 'MM/DD/YYYY HH24:MI:SS'));
COMMIT;

SET DEFINE OFF;
Insert into TB_USER   (ID, NAME, CODE) Values   (0, NULL, 'ALL');
COMMIT;